package po;

public class LogModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_verify_log.id
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_verify_log.app_id
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_verify_log.thirdparty_id
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    private Integer thirdpartyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_verify_log.trace_id
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    private String traceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_verify_log.mobile
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_verify_log.cert_number
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    private String certNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_verify_log.name
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_verify_log.image_path
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    private String imagePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_verify_log.request_ip
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    private String requestIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_verify_log.response_ip
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    private String responseIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_verify_log.http_code
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    private String httpCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_verify_log.request_body
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    private String requestBody;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_verify_log.response_body
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    private String responseBody;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column face_verify_log.elapsed_time
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    private Integer elapsedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_verify_log.id
     *
     * @return the value of face_verify_log.id
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_verify_log.id
     *
     * @param id the value for face_verify_log.id
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_verify_log.app_id
     *
     * @return the value of face_verify_log.app_id
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_verify_log.app_id
     *
     * @param appId the value for face_verify_log.app_id
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_verify_log.thirdparty_id
     *
     * @return the value of face_verify_log.thirdparty_id
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    public Integer getThirdpartyId() {
        return thirdpartyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_verify_log.thirdparty_id
     *
     * @param thirdpartyId the value for face_verify_log.thirdparty_id
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    public void setThirdpartyId(Integer thirdpartyId) {
        this.thirdpartyId = thirdpartyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_verify_log.trace_id
     *
     * @return the value of face_verify_log.trace_id
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    public String getTraceId() {
        return traceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_verify_log.trace_id
     *
     * @param traceId the value for face_verify_log.trace_id
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    public void setTraceId(String traceId) {
        this.traceId = traceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_verify_log.mobile
     *
     * @return the value of face_verify_log.mobile
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_verify_log.mobile
     *
     * @param mobile the value for face_verify_log.mobile
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_verify_log.cert_number
     *
     * @return the value of face_verify_log.cert_number
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    public String getCertNumber() {
        return certNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_verify_log.cert_number
     *
     * @param certNumber the value for face_verify_log.cert_number
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    public void setCertNumber(String certNumber) {
        this.certNumber = certNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_verify_log.name
     *
     * @return the value of face_verify_log.name
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_verify_log.name
     *
     * @param name the value for face_verify_log.name
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_verify_log.image_path
     *
     * @return the value of face_verify_log.image_path
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_verify_log.image_path
     *
     * @param imagePath the value for face_verify_log.image_path
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_verify_log.request_ip
     *
     * @return the value of face_verify_log.request_ip
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    public String getRequestIp() {
        return requestIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_verify_log.request_ip
     *
     * @param requestIp the value for face_verify_log.request_ip
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    public void setRequestIp(String requestIp) {
        this.requestIp = requestIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_verify_log.response_ip
     *
     * @return the value of face_verify_log.response_ip
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    public String getResponseIp() {
        return responseIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_verify_log.response_ip
     *
     * @param responseIp the value for face_verify_log.response_ip
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    public void setResponseIp(String responseIp) {
        this.responseIp = responseIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_verify_log.http_code
     *
     * @return the value of face_verify_log.http_code
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    public String getHttpCode() {
        return httpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_verify_log.http_code
     *
     * @param httpCode the value for face_verify_log.http_code
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    public void setHttpCode(String httpCode) {
        this.httpCode = httpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_verify_log.request_body
     *
     * @return the value of face_verify_log.request_body
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    public String getRequestBody() {
        return requestBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_verify_log.request_body
     *
     * @param requestBody the value for face_verify_log.request_body
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    public void setRequestBody(String requestBody) {
        this.requestBody = requestBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_verify_log.response_body
     *
     * @return the value of face_verify_log.response_body
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    public String getResponseBody() {
        return responseBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_verify_log.response_body
     *
     * @param responseBody the value for face_verify_log.response_body
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    public void setResponseBody(String responseBody) {
        this.responseBody = responseBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column face_verify_log.elapsed_time
     *
     * @return the value of face_verify_log.elapsed_time
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    public Integer getElapsedTime() {
        return elapsedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column face_verify_log.elapsed_time
     *
     * @param elapsedTime the value for face_verify_log.elapsed_time
     *
     * @mbggenerated Sat Mar 04 09:43:55 CST 2017
     */
    public void setElapsedTime(Integer elapsedTime) {
        this.elapsedTime = elapsedTime;
    }
}